# Project Information
site_name: Spectroscopies in Novel Superconductors 2026 â€“ Santa Fe
site_url: https://SNS2026.github.io


# Mkdocs Theme (Material Mkdocs)
theme:
  name: material
  palette:
    primary: "blue"
    accent: "blue"
  features:
    - navigation.tabs
    - navigation.top

markdown_extensions:
  - attr_list
  - md_in_html

nav:
  - Overview: index.md
  - About: about.md
  - Participate: participate.md
  - Program: program.md
  - Venue/Travel: location.md
  - Contact: contact.md

