# Project Information
site_name: Spectroscopies in Novel Superconductors 2026 â€“ Santa Fe
site_url: https://sns2026.org

# Mkdocs Theme (Material Mkdocs)
theme:
  name: material
  custom_dir: docs/overrides
  locale: en
  icon:
    logo: material/atom-variant
  favicon: assets/images/favicon_32.png
  
  font:
    text: SN Pro

  palette: 
    - scheme: LANL_light

  features:
#    - announce.dismiss
#    - navigation.instant
#    - navigation.instant.progress
#    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
#    - navigation.sections
    - content.tabs.link

nav:
  - Home: index.md
  - About: 
    - 'Local Committees': local_committees.md
    - 'International Committees': int_committees.md
    - 'Conference Policies': policies.md
  - Participate: 
    - Registration: register.md
    - 'Abstract Submission': abstracts.md
    - 'Visa Information': visa.md
  - Program: 
    - Schedule: schedule.md
  - Attending: 
    - Venue: venue.md
    - Location: location.md
    - Travel: travel.md
    - Lodging: lodging.md
  - Excursions: excursion.md
  - Contact: contact.md


copyright: Copyright &copy; 2026 SNS

extra:
  generator: false
#  homepage: https://sns2026.org

extra_css:
  - stylesheets/extras.css

markdown_extensions:
  - attr_list
  - md_in_html
  - abbr
  - admonition
  - def_list
  - footnotes
  - toc:
      permalink: true

  # Python Markdown Extensions
#  - pymdownx.arithmatex:
#      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
